### PR TITLE
Looking for Epic Android Ninjas

### PR DESCRIPTION
**Pull request by Jayroo5245**
Hello @Fleker ,

You have some seriously impressive github repos. I am a Senior Manager at Capital One and looking additional Android Ninjas like yourself.

I was wondering if you had 10-15 # minutes to chat?
 
Looking forward to hearing from you, here is more about me if interested: https://www.linkedin.com/in/jaredsheehan
 
Thanks!
 
Jared Sheehan
jared.sheehan@capitalone.com

### CODE REVIEW

**Comment by Fleker** [comment]
Sorry, I'm not interested.

**Comment by Jayroo5245** [comment]
Hey @Fleker No problem at all. You have a very interesting profile and 63 repo's is quite impressive. You sure you don't want to have a quick call? I'd like to connect either way. No love for sending you a PR instead of an Email? =)

**Comment by Fleker** [comment]
Sure we can organize a quick call on Friday perhaps.

**Comment by Jayroo5245** [comment]
Sure that sounds like a plan. When is good for you @Fleker? How should i reach you?

**Comment by Fleker** [comment]
You can send an email at handnf@gmail.com to discuss the details.

-Nick

**Pull request closed without merging**
